on:
  push:
    branches:
      - develop

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: node-test
          pull-request-title-pattern: "RELEASE/${version}"
          pull-request-header: ":robot: I have created a release"
