name: "sync-release"
on:
  push:
    branches:
      - main # or `master`, depending on the branch used for release
jobs:
  sync-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Sync PR to develop branch
        env:
          GH_TOKEN: ${{ github.token }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name $GITHUB_ACTOR
          git config user.email $GITHUB_ACTOR@users.noreply.github.com
          gh pr create -a $GITHUB_ACTOR -B develop -t "Main to Develop" -b "Syncing the latest release on main branch to develop"
          gh pr merge --admin --merge
